services:
  mongo:
    container_name: mongo
    image: mongo:7.0.14
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - common

networks:
  common:
    external: true
