version: "3.8"
services:
    node:
      container_name: node-app
      build: .
      user: "1000:1000"
      volumes:
          - ./src:/app
      ports:
          - "3000:3000"
      environment:
          - NODE_ENV=production
          - PORT=${PORT}
          - MONGO_URI=${MONGO_URI}
      networks:
          - backend

networks:
    backend:
      external: true